language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
  - issue#01
  - issue#02
  - issue#03
notifications:
  email:
    recipients:
    - diana.gtf88@gmail.com
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS bd;'
script:
#Test unitario y de integracion en develop
- mvn verify --settings settings.xml
